version: '3'

services:
  input-pod:
    image: ${DREG}ariqbasyar/fogbus2-fogverse:user
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./logs/:/workplace/fogverse-app/logs/
      - ./videos/:/workplace/fogverse-app/videos/
      - ./results/:/workplace/fogverse-app/results/
    working_dir: /workplace/fogverse-app
    command: ['producer.py']
    env_file: .docker-compose.env
