version: '3'

services:
  jetson-pod:
    image: ariqbasyar/fogverse:inference-gpu-jetson-sm
    volumes:
      - ./logs/:/app/logs/
      - ./yolov5-6.0/:/app/yolov5/
    environment:
    - CONSUMER_SERVERS=${LOCAL_KAFKA}
    - PRODUCER_SERVERS=${LOCAL_KAFKA}
    - SCENARIO=4
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 2800M
        reservations:
          devices:
            - capabilities: [gpu]
