version: '3'

services:
  jetson-pod:
    image: ariqbasyar/fogbus2-fogverse:CCTVInference
    volumes:
      - ./logs/:/workplace/fogverse-app/logs/
      - ./yolov7/:/workplace/fogverse-app/yolov7/
      - ./yolov7crowdhuman.pt:/workplace/fogverse-app/yolov7crowdhuman.pt
    working_dir: /workplace/fogverse-app
    command: ['inference.py']
    env_file: .docker-compose.env
    network_mode: host
