version: '3'

services:
  executor-pod:
    image: ${DREG}ariqbasyar/fogbus2-fogverse:CCTVInference
    volumes:
      - ./logs/:/workplace/fogverse-app/logs/
    working_dir: /workplace/fogverse-app
    command: ['inference.py']
    env_file: .docker-compose.env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
