version: '3'

services:
  executor-pod:
    image: ${DREG}ariqbasyar/fogbus2-fogverse:CCTVInference
    volumes:
      - ./logs/:/workplace/fogverse-app/logs/
      - ./yolo7crowdhuman.pt:/workplace/fogverse-app/yolo7crowdhuman.pt
    working_dir: /workplace/fogverse-app
    command: ['inference.py']
    env_file: .docker-compose.env
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
