ARG DREG
FROM ${DREG}ariqbasyar/opencv:v4.8.1.78-py3.9.18

RUN --mount=type=cache,target=/var/cache/apt_update apt-get update \
    && apt-get install -y --no-install-recommends \
        build-essential \
        ca-certificates \
        ccache \
        cmake \
        libjpeg-dev \
        libpng-dev && \
    rm -rf /var/lib/apt/lists/*

RUN --mount=type=cache,target=/root/.cache pip install \
        torch torchvision