FROM python:3.9-slim-bookworm

ENV TZ=Asia/Jakarta

RUN --mount=type=cache,target=/var/cache/apt_update apt update \
    && apt install -y --no-install-recommends \
        python-is-python3 \
        python3-pip \
        python3-dev \
        curl \
        git \
        vim \
        ffmpeg libsm6 libxext6 \
    && rm -rf /var/lib/apt/lists/*

RUN --mount=type=cache,target=/root/.cache pip install \
    numpy opencv-python
